- config/settings.py
- templates/header.html
Dans cette PR, j'ai peaufiné le header avec :
- ajout d'un badge "beta"
- ajouter le bon intitulé sur le logo avec la Marianne
- ajouter un lien pour créer un diagnostic car ça n'etait plus accessible partout depuis le site (ça me semblait une bonne idée au vu du changement de la navigation - mais on peut en rediscuter).
Variables configurées dans l'admin
> Améliorer le header : badge beta + logo intitulé + lien créer un diag

- config/settings.py
- templates/footer.html
- templates/header.html
- templates/index.html
Mise en place du DSFR pour le footer.
J'ai mergé la branche `feature/improve-header` dans cette PR, afin de recuperer la config de la description du footer depuis l'admin, il faut donc juste regarder le dernier commit.
à rediscuter si besoin : 
- Je n'ai pas ajouté le plan du site : je trouvais ça un peu étonnant de ne mettre que 3 liens.
- J'ai repris la phrase pour l'acces au code opensource de la startup d'etat ma cantine.
> ntégrer le nouveau design - footer

- templates/index.html
Il manquait juste l'import d'un fichier css lié aux icones  - suite à la MAJ du DSFR.
> import missing icon.css file for the DSFR to work properly after MAJ

- public_data/management/commands/build_administrative_layers.py
Résoud l'erreur suivante lors de l'éxécution de la commande `build_administrative_layers`:
```python
django.core.exceptions.FieldError: Cannot resolve keyword 'scot_name' into field.
```
> Fix du build des couches administratives

- project/models/project_base.py
- public_data/management/commands/build_commune_data.py
- utils/db.py
Résoud l'erreur :
```python
AttributeError: 'int' object has no attribute 'sq_m'
```
Qui a lieu lors de l'éxécution de la commande `python manage.py build_commune_data`
> Fix de la valeur intersection_area parfois égale à 0 au lieu de Area(0)

- public_data/management/commands/build_administrative_layers.py
Résoud les erreurs:
```python
django.db.utils.IntegrityError: null value in column "name" of relation "public_data_scot" violates not-null constraint
```
et 
```python
links[scot_name]["dept_id_list"].add(dept_id)
~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'dept_id_list'
```
⚠️ (à merger après https://github.com/MTES-MCT/sparte/pull/48)
> Divers fix sur la fonction Load Scot

- config/cache_backends.py
- config/settings.py
Resoud l'erreur:
```python
AttributeError at /project/nouveau
'DummyCache' object has no attribute 'delete_pattern'
```
Pas testé en profondeur, mais c'est le dummy cache d'une autre lib similaire à celle qu'on utilise, django-redis-cache:
https://github.com/sebleier/django-redis-cache/blob/master/redis_cache/backends/dummy.py
Celui de la lib qu'on utiise a été supprimé en 4.2:
https://github.com/jazzband/django-redis/blob/master/CHANGELOG.rst#django-redis-420-2015-07-03
> Fix redis dummy cache

- project/models/__init__.py
- project/models/create.py
Résoud l'erreur:
```python
ImportError: cannot import name 'Project' from partially initialized module 'project.models' (most likely due to a circular import) (/app/project/models/__init__.py)
```
> Fix erreur d'import circulaire

- project/models/project_base.py
- project/templates/project/list.html
- project/views/crud.py
- Supprime le queryset redondant avec la fonction get_queryset (6 secondes de temps CPU économisé avec une dizaine de project)
- Cache la surface des territoires de la liste des résultats (36 requêtes SQL économisé avec une dizaine de project, un peu plus de 1 seconde de temps CPU économisé)
En moyenne sur mon poste, le temps de chargement passe de 7 secondes à 200ms.
@smdsgn Est-ce que tu pense qu'on peut supprimer la surface de la liste ?
> Résolution lenteur de chargement de la page "Mes diagnostics"

- project/models/project_base.py
- public_data/management/commands/build_artificial_area.py
- public_data/management/commands/build_commune_data.py
- public_data/management/commands/load_ocsge.py
- public_data/management/commands/setup_dept.py
- public_data/models/couverture_usage.py
- Calcule les millesimes d'OCSGE disponibles d'un projet en se basant sur les millesimes disponibles pour chaque departements des villes composant le projet
- Ajoute un filtre par departement aux fonctions faisant référence à la table OCS GE directement, pour éviter les problèmes de superposition avec les limites administratives des departements voisins
- Ajoute la fonction manquante clean à l'OCS GE Essonne
- Ajoute le fonction calculate_fields manquante à l'OCS GE Essonne et Seine-Et-Marne
-----
Pour déployer, deux options:
- Faire un restore et éxécuter mep_440
- Executer les commandes suivantes:
- python manage.py load_ocsge --item=EssonneOcsge2018
- python manage.py load_ocsge --item=EssonneOcsge2021
- python manage.py load_ocsge --item=SeineEtMarneOcsge2017
- python manage.py …
> Multiple fix 4.4

- documentation/templates/documentation/faq.html
- documentation/views.py
- home/templates/home/privacy.html
- home/views.py
- required_parameters.json
- scalingo.json
A faire après le merge de cette PR :
->  `betagouv-redirections.osc-fr1.scalingo.io.`
> Changement de sous-domaine -> mondiagartif.beta.gouv.fr

- brevo/connectors.py
Certains endpoints retournent d'autres code que `204`(200, 201) donc cette fonction retournait souvent une erreur
`response.ok` retourne `True` si le `status_code` est inférieur à 400
----
Erreur sur sentry: https://sentry.incubateur.net/organizations/betagouv/issues/57855/events/c3f6bf28301b42c0ada8716dbebb8d84/
> Supprime fausse erreur dans le connecteur brevo

- project/charts.py
- project/templates/project/partials/artif_detail_couv_chart.html
- project/templates/project/partials/artif_detail_usage_chart.html
- project/templates/project/partials/household_comparison_conso.html
- project/templates/project/partials/pop_comparison_conso.html
- project/templates/project/partials/zone_urba_aggregated_table.html
- project/templates/project/partials/zone_urba_auu_table.html
- project/templates/project/partials/zone_urba_n_table.html
- project/templates/project/report_artif.html
- project/templates/project/report_discover_ocsge.html
- project/templates/project/report_synthesis.html
- trajectory/templates/trajectory/partials/graphic.html
US : https://app.clickup.com/t/8693tw2h4
---
- 0 décimales pour les nombres clefs / totaux
- 1 décimales pour les autres nombres hors graphiques
- 2 décimales pour les nombres dans les graphiques
Exemple Asnière sur seine:
Avant Artif
Après Artif
> Homogénéisation du nombre de décimales

- project/charts.py
- project/templates/project/partials/artif_cities_map.html
- project/templates/project/partials/artif_territory_map.html
- project/templates/project/report_artif.html
- project/views/map.py
US : https://app.clickup.com/t/8693u4e33
----
avant
après
avant
après
avant
après
couverture
avant
après
usage
avant
après
avant
après
> Changements page artificialisation - Retours datactivist

- public_data/management/commands/mep_47.py
- public_data/management/commands/mep_5.py
Supprime les `DataSource` avant de les charger afin d'éviter un conflit avec les sources existantes pour les gers, et celles nouvellement chargées.
> Fix commande de MEP V5.0

- project/views/report.py
Avant (auch)
Après (auch)
Avant (CA Grand Auch Cœur de Gascogne)
Après (CA Grand Auch Cœur de Gascogne)
> Remplace l'histogramme de conso annuelle par un diagramme en bar

- .slugignore
> Suppression warning slugignore des builds de container sur scalingo

- diagnostic_word/renderers.py
- project/charts/ObjectiveChart.py
- project/templates/project/partials/report_target_2031_graphic.html
- project/views/report.py
Avant : 
- valeur de 10% retournait 10% du total de consommation sur la période de référence comme valeur de "droit à consommer"
Après : 
- valeur de 10% retourne 90% du total de consommation sur la période de référence comme valeur de "droit à consommer" (réduction de 10%)
-----
La PR corrige également un bug : lors du rechargement de la valeur de réduction par HTMX, le total de la période de référence était éronné, le total de la conso sur la période du diagnostic était affiché au lieu du total de la période de référence.
---- 
Testable ici : https://sparte-staging-pr371.osc-fr1.scalingo.io/
> Inversion de la logique de réduction du graphique / tableau trajectoire

- config/settings.py
- config/storages.py
- project/admin.py
- project/models/create.py
- project/models/project_base.py
- project/tasks/project.py
- public_data/management/commands/build_shapefile.py
- public_data/management/commands/export_gpu.py
- public_data/storages.py
- Pour les communes : arrêt de la génération des fichiers
-`theme_map_conso` 1,25mo
-`theme_map_artif`  1,25mo
- Pour les territoires sans OCS GE, arrêt de la générations des fichiers :
- `theme_map_understand_artif` 1.57mo
- `theme_map_gpu` 1.21mo
- `theme_map_fill_gpu` 1.19mo
- Pour les territoires sans GPU, arrêt de la générations des fichiers :
- `theme_map_gpu` 1.21mo
- `theme_map_fill_gpu` 1.19mo
- Amélioration de la qualité de l'image de couverture (en demandant au WMTS un niveau de zoom supérieur).
- Passage des images utilisant de l'orthophoto du format png au format jpg (plus efficace pour des images type raster):
- `cover` : 1.25mo -> 130.27 Ko
- `theme_map_fill_gpu`: 1.19mo -> 141ko
- `theme_map_gpu`: 1.21mo -> 148ko
- `theme_map_understand_artif`: 1.57mo -> 200ko
- …
> Reduction de la taille des images des diagnostics

- project/views/report.py
Rajouté dans #386, cause des erreurs `IntegrityError` lorsque l'utilisateur utilise un mail déjà existant
> Supprime l'overide d'email pendant le téléchargement d'un diag

- project/charts/UsagePieChart.py
Corriger le titre du graphique répartition de l'usage des sols. 
Titre actuel: Répartition de la couverture des sols en {project.last_year_oscge}
Titre souhaité: Répartition de l'usage des sols  en {project.last_year_oscge}
Avant:
Après:
> Corriger le titre du graphique répartition de l'usage des sols

- public_data/migrations/0170_auto_20240607_1350.py
Retourne une erreur `DoesNotExist` pendant l'exécution de tests.
> Fix de la migration de suppression de l'EPCI hamp

- public_data/domain/artificialisation/use_case/CalculateCommuneArtificialAreas.py
- public_data/management/commands/build_shapefile.py
- public_data/management/commands/fix_is_artif_carriere.py
- public_data/management/commands/load_shapefile.py
- public_data/tasks.py
- public_data/test/test_build_shapefile.py
> Supprime les carrières de l'artif

- project/models/project_base.py
Resoud temporairement le problème en supprimant l'erreur 500, mais comme il n'y a pas d'objets OcsgeDiff, la page artif affiche toujours des graphiques vides.
> Fix erreur 500 en l'absence de donnée OcsgeDiff

- project/charts/ObjectiveChart.py
- project/templates/project/partials/report_target_2031_graphic.html
> Ajout plot band "période de référence" graphique trajectoire

- public_data/migrations/0174_auto_20240615_1835.py
Supprime la migration qui corrige les géométries des communes à partir des nouvelles données Cerema
La migration n'a pas assez de mémoire pour s'éxécuter dans nos environnements, et elle bloque les nouvelles migrations
> Suppression de migration : erreur de mémoire

- project/tasks/project.py
Exemple avec la carte "Comprendre l'artficialisation" :
Avant 
Après
> Amélioration du contraste des emprises sur le fond de carte OpenStreetMap

- project/models/project_base.py
Fixes #580 
----
Exemple avec Cazouls d'Herault.
Zonages environnant : 
Emprise de la commune : 
----
Les bordures intersectent légérement les zonages voisins, et la fonction `has_zonage_urbanisme` retournait `True`
> Masque l'onglet zonage d'urbanisme quand l'emprise du diagnostic n'en contient pas

- metabase/admin.py
- public_data/admin/CeremaAdmin.py
- public_data/admin/CommuneAdmin.py
- public_data/admin/CommunePopAdmin.py
- public_data/admin/DepartementAdmin.py
- public_data/admin/EpciAdmin.py
- public_data/admin/OcsgeAdmin.py
- public_data/admin/OcsgeArtificialAreaAdmin.py
- public_data/admin/OcsgeCommuneDiffAdmin.py
- public_data/admin/OcsgeCommuneSolAdmin.py
- public_data/admin/OcsgeDiffAdmin.py
- public_data/admin/OcsgeZoneConstruiteAdmin.py
- public_data/admin/RegionAdmin.py
- public_data/admin/ScotAdmin.py
- public_data/admin/SudocuhAdmin.py
- public_data/admin/SudocuhEpciAdmin.py
Erreur de CSP, mais a priori non bloquant car ça concerne une fonctionnalité de l'admin que nous n'utilisions pas.
> Remplace GeoModelAdmin (déprécié sur django 5) par GISModelAdmin

- airflow/include/admin_express/sources.json
- airflow/include/sql/sparte/macros/admin_express/epci.sql
- airflow/include/sql/sparte/models/admin_express/epci.sql
- airflow/include/sql/sparte/models/admin_express/epci_guadeloupe.sql
- airflow/include/sql/sparte/models/admin_express/epci_guyane.sql
- airflow/include/sql/sparte/models/admin_express/epci_martinique.sql
- airflow/include/sql/sparte/models/admin_express/epci_metropole.sql
- airflow/include/sql/sparte/models/admin_express/epci_reunion.sql
- airflow/include/sql/sparte/models/admin_express/schema.yml
> Ajout du chargement des EPCI au dag ingest_admin_express

- airflow/include/sql/sparte/macros/delete_from_this_where_field_not_in.sql
Nécessaire pour les models incrementaux de dbt qui ont un hard delete en post-hook : l'ancienne requête de delete pouvait prendre plusieurs heures.
> Amélioration des performances du delete des tables incremental (dbt)

- project/templates/project/components/dashboard/synthese.html
> Simplification des titres de la section artif de la synthèse

- public_data/views.py
> Changement d'unité des surfaces des objets OCS GE en ha dans l'explorateur des zonages d'urbanisme

- airflow/dags/create_ocsge_vector_tiles.py
Passage de "--no-tile-size-limit" à "--coalesce-densest-as-needed"
-> Réduit la taille des tuiles en nombre de features
Suppression de "--no-tiny-polygon-reduction",
Evite de former des petits carrés 
La doc : 
```
Don't combine the area of very small polygons into small squares that represent their combined area.
```
Passage de "--base-zoom=10" à "--base-zoom=11"
Niveau de zoom à partir duquel tous les détails sont affichés
> Amélioration de la configuration tippecanoe

- airflow/include/sql/sparte/models/for_app/for_app_region.sql
> Fix typo sur la table for_app_region: logement_vacants_available au lieu de logements_vacants_available

- airflow/include/container.py
Reverts MTES-MCT/sparte#837 qui retourne l'erreur suivante en prod : 
```python
TypeError: cannot pickle 'cryptography.hazmat.bindings._rust.openssl.rsa.RSAPublicKey' object
```
> Revert "Ajout des options cnopts pour la connection au SFTP de l'IGN"

- assets/scripts/components/layout/Dashboard.tsx
- assets/scripts/components/layout/Footer.tsx
- assets/scripts/components/layout/Header.tsx
- assets/scripts/components/layout/Navbar.tsx
- assets/scripts/components/layout/TopBar.tsx
- assets/scripts/components/ui/ButtonToggleNavbar.tsx
- assets/scripts/hooks/useWindowSize.ts
- assets/scripts/store/navbarSlice.ts
- assets/scripts/store/store.ts
- package-lock.json
- package.json
Repris de #899 pour la création de l'app review
**Menu principal version mobile:**
**Sidebar dashboard repliable en desktop:**
**Sidebar dashboard mobile:**
=> La sidebar est affichée au dessus du contenu en mobile, un overlay masque le contenu et le scroll sur le contenu est bloqué.
On facilite le clique sur les liens de téléchargement en version mobile. Il n'y a plus d'effet d'apparition des liens au hover en mobile, ils sont intégrés directement dans le scroll de la sidebar.
**Footer version mobile:**
> Amélioration du responsive

- assets/scripts/components/map/ocsge/constants/colors.tsx
- assets/scripts/components/map/ocsge/constants/cs_and_us.tsx
> Hotfix Carte OCS Ge : ajout de la couleur manquante pour CS2.2.2

- airflow/include/sql/sparte/models/ocsge/occupation_du_sol_with_artif.sql
Problème de performance avec `LEFT JOIN LATERAL`.
Conséquence du revert : restreint les départements d'ocsge eux départements pour lesquels l'artif a été calculée
> Revert "Correctif artif x occupation du sol : permet une valeur non officielle de l'artif"

- assets/scripts/components/features/status/OcsgeStatus.tsx
- assets/scripts/components/layout/Dashboard.tsx
- assets/scripts/components/pages/Artificialisation.tsx
- assets/scripts/components/pages/Synthese.tsx
- assets/scripts/hooks/useArtificialisation.ts
- assets/scripts/services/types/land.tsx
- public_data/models/administration/LandModel.py
- Suppression de la dépendance à `ProjectData` de `useArtificialisation ` -> comme on souhaite passer sur des diagnostics territoriaux il faudrait qu'on évite d'ajouter des dépendances à Project si on peut
- Passé le status OCS GE à `routeWrapper` pour l'affichage conditionnel de la page OCS GE. J'ai utilisé le boolean `has_ocsge` de `LandData`, mais il faudrait utiliser le status complet pour afficher un message qui a du sens / masquer les territoires pas complétement couvert par l'OCS GE (ça reste très minoritaire pour la MEP donc pas besoin de les prendre en compte dès maintenant)
- Déplacé les appels aux hooks de donnée au plus proche de leur utilisation
- Supprimé le `to_representation ` temporaire de `LandModelSerializer ` -> la donnée a été ajoutée à la table via DBT
> Prise en compte du cas où le territoire n'a pas d'OCS GE

- home/templates/home/home.html
- required_parameters.json
- users/tests/parameters.json
La valeur de JOTFORM_URL a été remplacée directement en prod par celle de la PR, le renommage de cette PR est pour rendre la variable agnostique de l'outil.
> Remplace et renomme l'url de webinaire

- airflow/dags/update_brevo.py
This pull request makes a small update to the `import_brevo_contacts` function by removing the environment-based logic that selected different `list_ids` for production and non-production environments. Now, `list_ids` is always set to `[10]`, with a TODO comment indicating the intention to support different environments in the future.
* Removed conditional logic for setting `list_ids` based on the `ENVIRONMENT` variable; now always uses `[10]` and added a TODO comment for future environment support.…ortation des contacts
> Fix brevo : only import to list #10

- project/views/diagnostic/DiagnosticLogementVacantView.py
fixes #1305 
This pull request makes a small update to the `DiagnosticLogementVacantView.py` view, extending the `end_date_conso` value from 2022 to 2023 to match the `end_date`. This ensures consistency in the date ranges used for diagnostics.
- Updated `end_date_conso` to 2023 in `get_context_data` to align with the main `end_date`.
> Ajoute l'année 2023 au graphique de conso x logements vacants

- project/charts/ObjectiveChart.py
- project/charts/consommation/ConsoAnnualChart.py
Graphiques corrigés :
This pull request adjusts the display range for plot bands in two different chart classes to improve the visual alignment with the underlying data. The main changes involve updating the `from` and `to` values for the plot bands to better match the intended reference periods.
**Chart display improvements:**
* Updated the `plotBands` range in `ObjectiveChart` (`project/charts/ObjectiveChart.py`) by changing the `from` value from `-1` to `-0.5` and the `to` value from `9` to `9.5`, ensuring the reference period band aligns more accurately with the data.
* Updated the `plotBands` range in `ConsoAnnualChart` (`project/charts/consommation/ConsoAnnualChart.py`) by changing the `from` value from `0` to `-0.5` and the `to` value from `11` to `9.5`, for improved alignment of …
> Ajustement des bornes de la période de référence sur les graphiques

- project/views/crud.py
This pull request introduces a hotfix to the `ProjectAddLookALike` view to ensure it works correctly. The main change is the addition of an `object` property that returns the result of `get_object()` from the superclass.
Functional hotfix:
* Added an `object` property to the `ProjectAddLookALike` class in `project/views/crud.py` to ensure the view retrieves the correct object instance, addressing a compatibility or functionality issue.
> Fix addlookalike

- frontend/scripts/hooks/useMatomoTracking.ts
- frontend/types/globals.d.ts
- utils/templates/utils/matomo_code.html
This pull request refactors the Matomo analytics integration by updating both the frontend tracking logic and the HTML template. The changes simplify the tracking setup, remove the dependency on backend-provided configuration for Matomo, and standardize the use of the `_paq` array for tracking events. Additionally, a utility function for tracking custom events is introduced in the template, and debug logging is improved.
**Frontend tracking logic updates:**
- Removed the dependency on `useGetEnvironmentQuery` and environment-based Matomo container source; now, tracking is solely controlled by the presence of a meta tag (`matomo-enabled`). The tracking script uses the global `_paq` array to send page view and metadata events. [[1]](diffhunk://#diff-02072db4794d73a849e04d2c723e94c4ba440608e1 …
> fix: remplacer _mtm par _paq pour la gestion du suivi Matomo
