Dockerfile

Une PR pour ajouter le fix de ce matin qui faisait planter mon docker.

add 'libgdal-dev' to 'apt install' to make docker works on Lisa computer

---

.vscode/launch.json
bin/init_review_database.sh
config/settings.py
diagnostic_word/admin.py
diagnostic_word/renderers.py
diagnostic_word/views.py
project/utils.py
scalingo.json

Amélioration de l'export Word

---

diagnostic_word/renderers.py
project/charts.py
project/templates/project/partials/household_comparison_conso.html
project/templates/project/partials/pop_comparison_conso.html
project/templates/project/partials/surface_comparison_conso.html
project/views/report.py

US texte : Légendes 2 graphiques conso pour export
Clickup : https://app.clickup.com/t/860r99ydw

Feat/us texte légendes 2 graphiques conso pour export

---

CHANGELOG.md
project/charts.py
project/templates/project/report_synthesis.html

- https://app.clickup.com/t/869319ym1
- https://app.clickup.com/t/86932emvh

hotfix correct conso 2011 to 2020 and conso 2031

---

public_data/models/administration.py

Règles les problèmes soulevés ici:
https://app.clickup.com/t/860ptq15e

Fix fonctionnalité de recherche augmentée (staging)

---

public_data/models/administration.py

Règles les problèmes soulevés ici:
https://app.clickup.com/t/860ptq15e

Fix fonctionnalité de recherche augmentée (develop)

---

project/models/project_base.py
public_data/management/commands/load_ocsge.py
public_data/management/commands/remove_ocsge_data_gironde.py
public_data/management/commands/setup_dept.py

https://app.clickup.com/14136489

Ajout d'une commande pour supprimer les données OCS GE d'Arcachon

---

project/models/project_base.py

Bug dans clickup : https://app.clickup.com/t/8693a97w5

force decimal data

---

public_data/exceptions.py
public_data/management/commands/build_administrative_layers.py
public_data/urls.py
public_data/views.py

- Fix sonarcube hotspot on grid_view

use ApiView to fix hotspot

---

home/templates/home/home.html

US : https://app.clickup.com/t/8693jj0nz
----
AVANT 
APRES
----
AVANT
APRES

Changements page d'accueil - Retours DGALN

---

trajectory/templates/trajectory/partials/graphic.html
trajectory/views.py

US: https://app.clickup.com/t/8693jhrnh
----
Avant sans trajectoire
Après sans trajectoire
----
Avant avec trajectoire
Après avec trajectoire

Cache trajectoire conditionellement - Retours DGALN

---

home/templates/home/home.html
project/templates/project/report_consommation.html

US: https://app.clickup.com/t/8693tx3ez
----
CEREMA, Céréma -> Cerema
Avant
Après
ENAF -> Espaces NAF
Avant
Après

Normalisation des écritures de Cerema et Espaces NAF

---

documentation/templates/documentation/faq.html

US : https://app.clickup.com/t/8693txuzb
----
Retire les attributs `target="_blank"` des liens vers les ancres de la FAQ.
Remplace `noopener` par `noreferrer `

Différencie les ancres des liens externes dans la FAQ

---

project/templates/project/partials/artif_detail_couv_chart.html
project/templates/project/partials/artif_detail_usage_chart.html
project/templates/project/partials/household_comparison_conso.html
project/templates/project/partials/pop_comparison_conso.html
project/templates/project/partials/surface_comparison_conso.html
project/templates/project/partials/zone_urba_aggregated_table.html
project/templates/project/partials/zone_urba_auu_table.html
project/templates/project/partials/zone_urba_n_table.html
project/templates/project/report_artif.html
project/templates/project/report_consommation.html
project/templates/project/report_discover_ocsge.html
project/templates/project/report_synthesis.html
project/templates/project/report_target_2031.html

US: https://app.clickup.com/t/8693tx3ez
----
Exemple du changement sur l'onglet consommation:

Remplacement des boutons "Données" en "Données et calcul"

---

public_data/management/commands/evaluate_city_area.py

https://github.com/MTES-MCT/sparte/pull/139

Fix: commande calcul des surfaces des communes 

---

config/settings.py

Déjà hotfixé : https://github.com/MTES-MCT/sparte/pull/143

Migre orthophoto de géoportail -> géoplateforme

---

project/charts.py
project/models/project_base.py
project/templates/project/report_consommation.html

US : https://app.clickup.com/t/8693u3frd
----
- Affichage de la légende sur le côté
- Ajout de l'année dans le tooltip
- Suppression des valeurs de déterminants inférieures à 0
- Ajout d'une ligne explicative dans l'astuce pour les valeurs "non renseignée"

Changements graphique "déterminants de la consommation"

---

project/templates/project/report_consommation.html

US : https://app.clickup.com/t/8693tyfgc

Indiquer "Données brutes" dans les graphs de la page conso sans calcul

---

project/charts.py
project/templates/project/report_consommation.html

US : https://app.clickup.com/t/8693tybeu

Changement graphique consommation d'espace annuelle

---

project/tasks/project.py
project/templates/project/partials/artif_zone_urba.html
project/templates/project/partials/zone_urba_aggregated_table.html
project/templates/project/partials/zone_urba_auu_table.html
project/templates/project/partials/zone_urba_fill_map.html
project/templates/project/partials/zone_urba_general_map.html
project/templates/project/partials/zone_urba_n_table.html
project/templates/project/report_urban_zones.html

US : https://app.clickup.com/t/8693jnrz8

Remplace "remplissage" par "taux d artificialisation"

---

public_data/management/commands/evaluate_city_area.py

fix(evaluate_city_area): fix command

---

documentation/templates/documentation/faq.html
documentation/views.py
home/templates/home/privacy.html
home/views.py
required_parameters.json
scalingo.json

Changement de sous-domaine

---

public_data/management/commands/mep_46.py
public_data/models/data_source_fixture.json

US : https://app.clickup.com/t/8693kpzkm https://app.clickup.com/t/8693kpzv1
----
Correction sur les shapefiles:
- Types des colonnes normalisés (couches couverture et usage du sol)

Ajout des données OCS GE 35 et 83

---

public_data/management/commands/mep_46.py
public_data/models/data_source_fixture.json

US : https://app.clickup.com/t/86942876r

Ajout OCS GE Val de Marne (94)

---

project/templates/project/report_consommation.html

US : https://app.clickup.com/t/8693u3q9h
----
Avant
Après

Ajout de sous-titre au graph de comparaison conso

---

project/charts.py
project/templates/project/partials/artif_detail_couv_chart.html
project/templates/project/partials/artif_detail_usage_chart.html
project/templates/project/partials/household_comparison_conso.html
project/templates/project/partials/pop_comparison_conso.html
project/templates/project/report_artif.html
project/templates/project/report_discover_ocsge.html
project/templates/project/report_synthesis.html
trajectory/templates/trajectory/partials/graphic.html

fix(*): homogeneize decimal number

---

project/charts.py
project/models/project_base.py
project/templates/project/partials/surface_comparison_conso.html
public_data/models/administration.py

US : https://app.clickup.com/t/8693u3p13
----
Avant
Après

Changement de l'unité du graphique "Consommation proportionnelle à la surface"

---

public_data/management/commands/build_artificial_area.py
public_data/management/commands/fix_artificial_area_missing_departement.py
public_data/management/commands/mep_452.py
public_data/models/data_source_fixture.json

Avant de merger :
----
Commandes à éxécuter :
`python manage.py mep_452`

OCS GE : ajout de 35, 83, 94 (production)

---

project/forms.py

US : https://app.clickup.com/t/86940aw7m

Update raise error logic

---

project/templates/project/partials/household_comparison_conso.html
project/templates/project/partials/pop_comparison_conso.html
project/templates/project/partials/surface_comparison_conso.html
project/templates/project/partials/zone_urba_aggregated_table.html
project/templates/project/partials/zone_urba_auu_table.html
project/templates/project/partials/zone_urba_n_table.html
project/templates/project/report_artif.html
project/templates/project/report_consommation.html
project/templates/project/report_discover_ocsge.html
project/templates/project/report_synthesis.html
trajectory/templates/trajectory/partials/graphic.html

US : https://app.clickup.com/t/860q2hna2
----
avant (conso)
après
avant (artif)
après

Add data tags to tables and graphs

---

project/templates/project/partials/household_comparison_conso.html
project/templates/project/partials/pop_comparison_conso.html
project/templates/project/partials/surface_comparison_conso.html
project/templates/project/report_consommation.html
project/templates/project/report_synthesis.html
project/templates/project/report_target_2031.html
trajectory/templates/trajectory/partials/graphic.html
trajectory/templates/trajectory/report_trajectory.html

Supprime les accents à Cerema

---

home/templates/home/home.html

Changement liste objectifs page d'accueil

---

project/views/map.py

Ajout des dates à la legende de la carte "Comprendre l'artif"

---

project/charts.py

2 decimales maximum pour les graphiques de démographies

---

project/templates/project/report_artif.html
project/views/report.py

Résolution du bug de surface et pourcentage du graphique "Artif nette entre x et x"

---

crisp/models.py
crisp/serializers.py
crisp/signals.py

Testable ici : https://sparte-staging-pr263.osc-fr1.scalingo.io/
Les notifications s'affichent sur ce channel : https://mattermost.incubateur.net/fabnum-mte/channels/sparte-crisp

Crisp Webhook

---

project/charts.py

Exemple avant / après pour la diagnostic de Auch
Images du bug en staging : 
Usage
Couverture
Preview du fix : 
Usage
Couverture

Bug fix : ré-ajoute les valeurs d'artif des tableaux de données "Evo de l'artif par usage / couverture"

---

assets/styles/index.css
home/templates/home/home_rapport_local.html
home/urls.py
home/views.py
static/assets/styles/main.css
templates/header.html

Ajout de la landing page du rapport local

---

home/templates/home/home_rapport_local.html

Mise à jour de la landing du page rapport local : remplacement de l'inscription newsletter par la recherche de territoire

---

brevo/connectors.py
home/views.py

Testable sur l'app review : https://sparte-staging-pr334.osc-fr1.scalingo.io/

Envoyer les inscrits à la newsletter à Brevo

---

project/tasks/project.py

Amélioration carte "Comprendre l'artif"

---

.github/workflows/pr.yml

https://docs.djangoproject.com/en/5.0/howto/upgrade-version/#resolving-deprecation-warnings

Ajout des warning de depréciation aux tests

---

public_data/models/ocsge.py

Fix migration

---

project/templates/project/partials/zone_urba_general_map.html

Correction du nom de la carte de présentation des zonages d'urbanisme

---

airflow/dags/update_app.py

Nouveaux paramètres airflow pour le dag `update_app`:
- `subset_geom` est une requête qui récupère une géométrie dans le data lake (la requête ne doit retourner qu'une seule géométrie)
- `use_subset ` défini si un subset de la table doit être chargée (autrement toute la table est chargée)

Ajout d'une fonctionnalité permettant de charger seulement une partie des données depuis airflow dans l'application

---

assets/scripts/components/charts/HighchartsMapOcsge.tsx

Avant 
Après (sur un environnement qui ne contient que la Gironde)

Suppressions des options de la carte de déploiement OCS GE

---

airflow/dags/update_app.py
airflow/include/sql/sparte/models/for_app/for_app_couverturesol.sql
airflow/include/sql/sparte/models/for_app/for_app_couvertureusagematrix.sql
airflow/include/sql/sparte/models/for_app/for_app_usagesol.sql

Rend possible de restore une BDD entièrement avec le dag update_app de airflow

Ajout des tables UsageSol, CouvertureSol et CouvertureUsageMatrix au dag update_app

---

assets/scripts/map_libre/events.js
project/serializers.py
project/views/map.py

Mise à jour de la carte interactive de l'artificialisation par commune

---

airflow/Dockerfile
airflow/packages.txt
airflow/tests/test_tippecanoe_cli.py

Ajout de tippecanoe au container d'airflow

---

users/apps.py
users/signals.py
utils/mattermost.py

+ remplace l'envoi de message mattermost de synchronous à fire and forget

Log un message à chaque connexion d'un superuser ou staff member sur mattermost

---

airflow/include/sql/sparte/models/for_app/for_app_departement.sql
airflow/include/sql/sparte/models/for_app/for_app_logementvacant.sql
airflow/include/sql/sparte/models/for_app/for_app_region.sql

+ fix des colonnes `autorisation_logement_available` et `logements_vacants_available`des tables `Departement`et `Region`

Ajout des pourcentages des privés et socials vacants sur le parc general

---

assets/scripts/components/map/ocsge/OcsgeMap.tsx

Carte OCS GE : change les trigger d'affichage des statistiques (barre horizontale)

---

airflow/include/sql/sparte/macros/utils/create_idx_if_not_exists.sql
airflow/include/sql/sparte/models/ocsge/artif.sql
airflow/include/sql/sparte/models/ocsge/occupation_du_sol.sql
airflow/include/sql/sparte/tests/no_duplicate_ingest_in_artif.sql
airflow/include/sql/sparte/tests/no_duplicate_ingest_in_occupation_du_sol.sql

- Rend les modèles incrementals
- Logique d'indexation des sources
- Logique de hard delete des sources modifiées
- Ajout de tests d'intégrités pour éviter les doublons

Optimisation des modèles occupation_du_sol et artif de DBT

---

airflow/dags/update_app.py
airflow/include/sql/sparte/models/admin_express/land.sql
airflow/include/sql/sparte/models/admin_express/land_departement.sql
airflow/include/sql/sparte/models/for_app/for_app_land.sql
airflow/include/sql/sparte/models/for_app/for_app_landartifstock.sql
airflow/include/sql/sparte/models/for_app/for_app_landartifstockindex.sql
airflow/include/sql/sparte/models/ocsge/calculated/stock/land/artif_land.sql
airflow/include/sql/sparte/models/ocsge/calculated/stock/land/artif_land_by_index.sql
airflow/include/sql/sparte/models/ocsge/land_millesimes.sql
assets/scripts/components/charts/GenericChart.tsx
assets/scripts/components/charts/ocsge/OcsgeGraph.tsx
assets/scripts/components/pages/Artificialisation.tsx
assets/scripts/services/types/land.tsx
project/api_urls.py
project/charts/artificialisation/ArtifMap.py
project/charts/artificialisation/__init__.py
public_data/models/administration/LandModel.py
public_data/models/artificialisation/LandArtifStock.py
public_data/models/artificialisation/LandArtifStockIndex.py

- Commune : pas de maille inférieure
- EPCI et SCOT : Communes
- Départements : EPCI ou SCOT
- Région : Départements
----
WIP

Ajout de la carte artif à la maille inférieure

---

home/templates/home/home.html

Remplacement du message "Nouveau" sur la page d'accueil pour mentionner l'application des seuils de l'artif

---

users/middleware.py

Revert "Revert "Permet à proconnect d'utiliser les endpoints d'api""

---

airflow/include/sql/sparte/models/for_app/for_app_land.sql
airflow/include/sql/sparte/models/ocsge/land_ocsge_status.sql
assets/scripts/components/features/status/OcsgeStatus.tsx
assets/scripts/components/layout/Dashboard.tsx
assets/scripts/components/ui/RouteWrapper.tsx
assets/scripts/services/types/land.tsx
public_data/models/administration/LandModel.py

et simplification du composant `RouteWrapper`

Ajout du status de disponibilité complet pour l'OCS GE

---

airflow/include/sql/sparte/models/ocsge/artif.sql
airflow/include/sql/sparte/models/ocsge/schema.yml

This reverts commit 315978e2b500a8c679e3f1b28f8f56ce9ac6af3e.

Suppression du fix temporaire sur le champs crit_seuil des données d'artif

---

home/templates/home/home.html

Remplace les h3 par des div sur la homepage

---

project/serializers.py
required_parameters.json
templates/footer.html
templates/header.html
users/tests/parameters.json

Renommer la FAQ en centre d'aide
